server-neo:
  image: arenstar/zenbot
  links:
    - mongodb
  command: ./zenbot.sh trade --paper bittrex.BTC-NEO --debug
  restart: always

server-mtl:
  image: arenstar/zenbot
  links:
    - mongodb
  command: ./zenbot.sh trade --paper bittrex.BTC-MTL --debug
  restart: always

server-ioc:
  image: arenstar/zenbot
  links:
    - mongodb
  command: ./zenbot.sh trade --paper bittrex.BTC-IOC --debug
  restart: always

mongodb:
  image: mongo:latest
  volumes:
    - /var/lib/mongodb/data/db:/data/db
  command: mongod --smallfiles
